server:
  port: 8080
  security:
    host:
      sms-center:
    #短信接口
    host: http://127.0.0.1:8073/api/sms/
#加入/demo前缀
#server:
#  servlet:
#    context-path: /first

spring:
  redis:
    database: 0
    host: 192.168.33.10
    password: root
    port: 6379

masterdb:
  druid:
    url: jdbc:mysql://rm-bp1wp84ot5b11c6q1o.mysql.rds.aliyuncs.com:3306/womaodev?useUnicode=true&autoReconnect=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: womaomain
    password: '@Womaojr'
#    url: jdbc:mysql://192.168.33.10:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
#    username: root
#    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    max-active: 20
    min-idle: 2
    initial-size: 2
    max-wait: 60000
    time-between-eviction-runs-millis:  60000
    min-evictable-idle-time-millis: 300000
    validation-query: select 1
    test-while-idle:  true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-open-prepared-statements: 20

