spring:
  profiles:
    #起作用的配置文件 application-{dev,test,product}.yml
    active: dev
    #active: test
    #active: product

#Mybatis
mybatis_config_file: mybatis-config.xml
mapper_path: /mapper/**.xml
type_alias_package: com.imooc.first.model

# 打印sql
logging:
  level:
    com.imooc.first.dao: DEBUG